# Generated by Django 2.0.5 on 2018-05-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifycode',
            name='mobile',
        ),
        migrations.AddField(
            model_name='verifycode',
            name='account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='帐号'),
        ),
    ]
