# Generated by Django 2.0.5 on 2018-05-10 14:09

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180510_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=froala_editor.fields.FroalaField(verbose_name='内容'),
        ),
    ]
